"""Add event fields

Revision ID: 031751350eb0
Revises: 81cbf21e0954
Create Date: 2026-08-05 19:03:45.114452

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "031751350eb0"
down_revision = "81cbf21e0954"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###

    with op.batch_alter_table("events", schema=None) as batch_op:

        batch_op.add_column(
            sa.Column(
                "ticket_price",
                sa.Float(),
                nullable=False,
                server_default="0"
            )
        )

        batch_op.add_column(
            sa.Column(
                "available_seats",
                sa.Integer(),
                nullable=False,
                server_default="0"
            )
        )

        batch_op.add_column(
            sa.Column(
                "organizer",
                sa.String(length=150),
                nullable=False,
                server_default="Admin"
            )
        )

        batch_op.add_column(
            sa.Column(
                "registration_deadline",
                sa.Date(),
                nullable=False,
                server_default=sa.text("'2026-12-31'")
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("events", schema=None) as batch_op:

        batch_op.drop_column("registration_deadline")
        batch_op.drop_column("organizer")
        batch_op.drop_column("available_seats")
        batch_op.drop_column("ticket_price")

    # ### end Alembic commands ###